// Public copy for the Managed Server Colocation section (EN / ID).
// Keep numbers out of this file — prices and specs live in ./config.ts.

const en = {
    meta: {
        title: "Server Colocation Jakarta | GPU & NVIDIA B200/B300 Colocation | GDI Consult",
        description:
            "Managed server colocation in Jakarta for enterprise, GPU and AI infrastructure. GDI manages facility selection, rack space, power, connectivity, installation, remote hands, reporting and NVIDIA H100, H200, B200 and B300 deployments.",
    },
    nav: "Data Center & Colocation",
    hero: {
        eyebrow: "Managed Data Center Services • Jakarta",
        h1: "Managed Server Colocation in Jakarta",
        p1: "One provider for rack space, power, connectivity, installation and ongoing server operations across multiple data-center facilities in Jakarta.",
        p2: "From standard 1U enterprise servers to high-density NVIDIA H100, H200, B200 and B300 infrastructure, GDI selects the appropriate facility and manages the deployment from installation to monthly reporting.",
        ctaPrimary: "Calculate Colocation Cost",
        ctaSecondary: "Request Infrastructure Quote",
        micro1: "1 server → full racks → 100+ GPU nodes",
        micro2: "Indicative pricing available instantly. Final technical validation is required for high-density GPU deployments.",
        tagline: "One provider. Multiple data centers. One point of responsibility.",
    },
    trust: [
        { title: "Multiple Facilities", desc: "GDI can allocate infrastructure across different partner data centers." },
        { title: "Single Point of Contact", desc: "One GDI team coordinates facility, network and on-site operations." },
        { title: "GPU-Ready Planning", desc: "Power and cooling requirements are evaluated before deployment." },
        { title: "Operational Reporting", desc: "Regular infrastructure, incident and service reporting for the customer." },
    ],
    manages: {
        title: "More Than Rack Space",
        intro: "Colocation becomes difficult when the customer has to coordinate separately with a data center, network provider, local engineer and hardware vendor. GDI provides one managed layer for the complete deployment.",
        cards: [
            { title: "Facility Selection", desc: "We match the server profile with suitable facilities based on rack capacity, power density, cooling, connectivity, security requirements and budget." },
            { title: "Rack & Power Allocation", desc: "GDI reserves the required rack units, power capacity, feeds and PDU configuration for the selected equipment." },
            { title: "Installation & Cabling", desc: "Server receiving, rack installation, power connection, network cabling, labeling and initial physical checks can be coordinated by GDI." },
            { title: "Connectivity", desc: "Internet bandwidth, domestic connectivity, international bandwidth, public IP, BGP and cross-connect requirements can be included in the deployment." },
            { title: "Remote Hands", desc: "Physical reboot, cable checks, visual inspection, component replacement and other approved on-site tasks can be coordinated without sending your own engineer to Jakarta." },
            { title: "Monitoring & Incidents", desc: "GDI becomes the operational coordination point for infrastructure incidents and escalates issues to the appropriate facility or network team." },
            { title: "Hardware Logistics", desc: "Optional receiving, inventory control, spare-parts handling, RMA coordination and hardware replacement support." },
            { title: "Reporting", desc: "Customers can receive recurring reports covering assets, incidents, maintenance, service activity and available infrastructure metrics." },
        ],
    },
    why: {
        title: "The Right Facility for the Right Server",
        p1: "Not every data center is suitable for every workload.",
        p2: "A standard 1U application server may only require a few hundred watts, while an NVIDIA DGX B200 can require up to approximately 14.3 kW and a DGX B300 approximately 14.5 kW of operating power, with significantly higher rack-density planning requirements.",
        p3: "Instead of forcing every customer into one facility, GDI can select from multiple partner locations and allocate the infrastructure according to the actual workload.",
        examples: [
            { title: "Standard Enterprise", desc: "Priority: cost efficiency, reliable connectivity, normal rack density." },
            { title: "Business Critical", desc: "Priority: redundant power/network options, stronger SLA requirements, controlled access and reporting." },
            { title: "AI / High Density", desc: "Priority: high power per rack, cooling capability, electrical design, rack depth/weight, high-speed network and expansion capacity." },
        ],
    },
    categories: {
        title: "Server Categories",
        intro: "Pick the profile closest to your hardware. You do not need exact rack engineering details — presets carry sensible defaults, and Custom lets you enter your own.",
        from: "From",
        perMonth: "/ month",
        perServerMonth: "/ server / month",
        setup: "One-time setup from",
        examples: "Examples",
        configure: "Configure",
        validation: "Facility validation required",
        powerProfile: "power profile",
        pricingPower: "pricing power",
        maxPower: "max system power",
        typicalPower: "typical power",
        planningPower: "planning value",
        rack: "Rack",
        presets: {
            "standard-1u": { desc: "Single-socket or dual-socket 1U compute servers for applications, web and general workloads." },
            "standard-2u": { desc: "2U compute servers with more storage bays or expansion cards, within the standard power allowance." },
            "storage-2u": { desc: "Storage appliances or CPU-dense systems above the standard power allowance. Priced with additional reserved power." },
            "gpu-4u-l40s": { desc: "PCIe GPU servers for inference and mid-size training. OEM designs vary, so this is an estimate preset, not a guaranteed electrical specification.", note: "Final price depends on the actual server PSU and measured / reserved power profile." },
            "dgx-h100": { desc: "8U air-cooled system with 8× H100 GPUs. High-density placement, engineering validation required." },
            "dgx-h200": { desc: "Same chassis and power envelope as DGX H100 with 8× H200 GPUs." },
            "dgx-b200": { desc: "NVIDIA B200 infrastructure requires data-center engineering beyond standard colocation. GDI evaluates rack layout, power feeds, cooling capacity, server weight, network design and expansion capacity before confirming the facility." },
            "dgx-b300": { desc: "For B300 deployments, GDI validates the electrical design, rack configuration, cooling profile and network architecture with the selected facility before installation." },
        } as Record<string, { desc: string; note?: string }>,
        badges: { "popular-ai": "Popular AI", "blackwell-ultra": "Blackwell Ultra" } as Record<string, string>,
        custom: { title: "Custom Server", desc: "Enter rack units, power, feeds, depth, weight and ports for any other system. Above 5 kW per server it is classified as high density; above 10 kW an engineering review is required before final quotation." },
    },
    ai: {
        eyebrow: "AI Infrastructure",
        h2: "Colocation for NVIDIA B200 & B300",
        p1: "Blackwell-class systems cannot be treated like standard rack servers. A DGX B200 occupies 10U and can require up to 14.3 kW. DGX B300 is also a 10U system and operates around the 14.5 kW class, with a 15 kW system maximum used for capacity planning.",
        p2: "At this density, available rack space is only one part of the problem. The facility must be able to support the required electrical design, cooling, airflow, rack weight, PDU or busbar architecture and high-speed network connectivity.",
        p3: "GDI evaluates these requirements across suitable partner facilities before confirming a deployment.",
        b200: ["10U", "14.3 kW max", "8× B200 GPUs", "High-density validation required"],
        b300: ["10U", "~14.5 kW operating class", "15 kW planning value", "8× B300 GPUs"],
        rackPlanning: "Rack planning",
        defaultRack: "Default: 2 systems per rack",
        specializedRack: "Specialized: 4 systems per rack — specialized high-density facility required, subject to engineering approval.",
        ctaPrimary: "Plan B200 / B300 Deployment",
        ctaSecondary: "Calculate 1–200 Servers",
    },
    calculator: {
        title: "Estimate Your Colocation Cost",
        intro: "Select your server type and quantity. We will estimate rack space, reserved power and monthly colocation cost. High-density GPU estimates are indicative and require final facility validation.",
        configure: "Configure",
        estimate: "Your estimate",
        serverType: "Server type",
        quantity: "Quantity",
        quantityHint: "1–200 servers",
        moreThanMax: "Need more than 200? Request a custom infrastructure plan.",
        contract: "Contract",
        months: "months",
        month: "month",
        longTerm: "Long-term and volume pricing may be available after facility confirmation.",
        connectivity: "Connectivity",
        bandwidth: {
            basic: "Shared / basic connectivity",
            domestic: "Domestic",
            international: "International",
            dedicated: "dedicated",
            custom: "Custom / BGP / Cross-connect",
        },
        fabric: "I need high-speed GPU cluster networking / InfiniBand",
        fabricNote: "Custom network quote required",
        site: "Redundancy / multi-site",
        siteOptions: { single: "Single facility", dr: "Primary + secondary / DR facility", recommend: "Not sure — let GDI recommend" },
        drScope: "What should be duplicated?",
        drScopeOptions: { all: "All servers", count: "Selected number of servers", custom: "Network only / custom" },
        drCount: "Servers at DR site",
        drCustomNote: "Custom DR design — priced in the final proposal.",
        drRecommendNote: "GDI will propose a single-site or multi-site design based on your requirements.",
        serviceLevel: "Service level",
        service: {
            core: { name: "GDI Core Management", price: "Included", items: ["Facility coordination", "Basic deployment coordination", "Incident escalation", "Monthly service report"] },
            remote: { name: "Managed Remote Operations", price: "+ Rp 2,400,000 / month / deployment", items: ["Priority coordination", "Up to an agreed remote-hands allowance", "Maintenance coordination", "Expanded monthly report"] },
            enterprise: { name: "Enterprise NOC / Mission Critical", price: "Custom quote", items: ["24/7 operational support scoped separately", "GPU clusters, multi-rack and regulated workloads"] },
        },
        customFields: {
            rackU: "Rack units (U)",
            powerWatts: "Expected / maximum power (W)",
            psuCount: "Number of PSUs",
            dualFeed: "Dual power feed (A+B)",
            depthMm: "Server depth (mm)",
            weightKg: "Weight (kg)",
            ports: "Required network ports",
            specialCooling: "Special cooling requirements",
            notes: "Model number / notes",
        },
        powerOverride: "Actual power per server (W, optional)",
        powerOverrideHint: "Leave empty to use the included power profile.",
        result: {
            monthly: "Estimated Monthly Colocation",
            perMonth: "/ month",
            profile: "Server profile",
            quantity: "Quantity",
            rackSpace: "Rack space",
            power: "Reserved server power",
            racks: "Estimated racks",
            facility: "Recommended deployment",
            setup: "Estimated one-time deployment",
            connectivity: "Connectivity",
            service: "Managed service",
            contractTotal: "Recurring estimate for",
            finalQuote: "Final quote",
            validation: "Facility engineering validation required",
            standardQuote: "Confirmed after facility availability check",
            quoteRequired: "Quote required",
            included: "Included",
            drSuffix: "incl. DR site",
            engineering: "Engineering review required before final quotation.",
        },
        facility: {
            standard: "Standard Enterprise Facility",
            "standard-extended": "Standard facility with extended power",
            "high-density-gpu": "High-Density GPU Facility",
            "high-density-ai": "High-Density AI Facility",
        } as Record<string, string>,
        tiers: {
            enterprise: { title: "Enterprise Infrastructure", desc: "Your deployment may qualify for dedicated racks, reserved power blocks and negotiated facility pricing. GDI will validate the architecture and request capacity from suitable partner facilities before issuing the final proposal." },
            "large-cluster": { title: "Large AI Cluster", desc: "Dedicated infrastructure engineering required." },
            "ai-factory": { title: "AI Factory / Large Cluster Planning", desc: "GDI will evaluate multi-rack power, cooling, network fabric, staging, spares and phased deployment." },
            "capacity-reservation": { title: "Enterprise Capacity Reservation", desc: "Facility capacity and deployment schedule must be confirmed before commercial commitment. Multi-megawatt capacity requires a formal facility capacity reservation." },
        } as Record<string, { title: string; desc: string }>,
        planningNote: "This is a planning estimate, not a binding quotation.",
        rackViz: { perRack: "Server load per rack", standard: "standard", highDensity: "high density", serversPerRack: "servers / rack" },
        ctaQuote: "Get Final Quote",
        ctaEnterprise: "Request Enterprise Quote",
        ctaSend: "Send Estimate to GDI",
        tooltips: {
            u: "Rack unit: 1U = 44.45 mm of vertical rack space.",
            kw: "Reserved electrical capacity for the server, not average consumption.",
            remoteHands: "On-site tasks performed by facility staff on your behalf.",
            bgp: "Border Gateway Protocol — announcing your own IP space / ASN.",
            crossConnect: "Physical cable between your rack and another party inside the facility.",
        },
    },
    rackPricing: {
        title: "Standard Colocation — Indicative Pricing",
        items: {
            "1u": { name: "1U Server", lines: ["Up to ~450 W profile", "Basic GDI coordination", "1 server"], cta: "Configure 1U" },
            "2u": { name: "2U Server", lines: ["Up to ~500 W profile", "Basic GDI coordination", "1 server"], cta: "Configure 2U" },
            quarter: { name: "Quarter Rack", lines: ["Approx. 10U class", "Power allowance depends on facility"] },
            half: { name: "Half Rack", lines: ["Approx. 20–22U class", "Power allowance depends on facility"] },
            full: { name: "Full Rack", lines: ["Approx. 42–45U class", "Standard-density power only"] },
        } as Record<string, { name: string; lines: string[]; cta?: string }>,
        footnote: "High-density GPU power is priced separately and should not be estimated from standard full-rack pricing.",
        addonsTitle: "Add-ons",
        addons: [
            "Extra 100 W (standard servers): Rp 420,000 / month",
            "Additional IPv4: from Rp 36,000 / month",
            "Additional LAN port: Rp 180,000 / month",
            "Additional standard power socket: Rp 180,000 / month",
            "OS installation assistance: Rp 420,000 / event",
            "Cross-connect, BGP, private circuit, IX, dark fiber, cloud connect, AI fabric: request quote",
        ],
        requestQuote: "Request quote",
    },
    serviceLevels: {
        title: "Managed Service Levels",
        intro: "Every level defines the responsibility boundary between GDI, the facility and your team.",
        core: { name: "GDI Core Management", badge: "Default", price: "Included in base estimate", items: ["Facility selection and coordination", "Deployment coordination", "Asset registration", "Incident escalation", "Maintenance coordination", "Basic monthly service report", "Single GDI commercial contact"] },
        remote: { name: "Managed Remote Operations", badge: "Optional", price: "From Rp 2,400,000 / month / deployment", items: ["Everything in Core", "Priority operational coordination", "Remote-hands allowance according to contract", "Physical checks and approved interventions", "Spare-parts / RMA coordination", "Expanded monthly report"] },
        enterprise: { name: "Enterprise NOC", badge: "Custom", price: "Custom quote", items: ["GPU clusters and multi-rack environments", "Regulated and business-critical workloads", "24/7 escalation requirements", "Custom incident response", "Multi-site infrastructure"], cta: "Design Enterprise SLA" },
    },
    process: {
        title: "Deployment Process",
        steps: [
            { title: "Requirements", desc: "We collect server models, quantities, power, connectivity, deployment date and operational requirements." },
            { title: "Facility Matching", desc: "GDI evaluates suitable partner facilities and available capacity in Jakarta / Greater Jakarta." },
            { title: "Technical Validation", desc: "Rack, electrical, cooling, network, weight and access requirements are checked before commitment." },
            { title: "Commercial Proposal", desc: "GDI issues one consolidated proposal for the selected infrastructure and managed services." },
            { title: "Deployment", desc: "Hardware receiving, rack installation, power, cabling and connectivity are coordinated according to the approved scope." },
            { title: "Operations", desc: "GDI manages ongoing coordination, incidents, remote hands, reporting and future expansion." },
        ],
    },
    reporting: {
        title: "Know What Is Happening to Your Infrastructure",
        copy: "GDI can consolidate operational information into a recurring infrastructure report, giving management one view of deployed assets, service activity and incidents across the selected data-center environment.",
        exampleTitle: "Example report contents",
        items: ["Customer / project and facility reference", "Asset inventory, rack location / U position where contractually allowed", "Allocated power and available power metrics", "Bandwidth / traffic summary", "Incidents opened / closed, downtime or SLA events reported by the facility", "Scheduled maintenance and remote-hands activity", "Hardware changes and spare-parts usage", "Access events", "Open risks, recommended actions, capacity / expansion notes"],
        note: "Metrics are included where data is available from the selected facility.",
    },
    multisite: {
        title: "One GDI Contract. Multiple Facilities.",
        copy: "For customers that do not want all infrastructure in one location, GDI can design deployments across separate partner data centers.",
        useCases: ["Primary + DR", "Production + backup", "Active + standby", "Network diversity", "Phased migration", "Capacity split", "AI compute at a high-density site + management/storage at another site"],
        disclaimer: "Actual geographic separation, latency, connectivity and failover architecture depend on the selected facilities and customer requirements.",
    },
    enterprise: {
        title: "Enterprise Deployments",
        copy: "From ten GPU nodes upward, GDI treats the project as dedicated infrastructure: reserved racks and power blocks, phased delivery, staging and spares. The calculator flags the tier automatically.",
        tiers: [
            { range: "10+ GPU nodes", title: "Enterprise Infrastructure", desc: "Dedicated racks, reserved power blocks and negotiated facility pricing after capacity request." },
            { range: "20+ GPU nodes", title: "Large AI Cluster", desc: "Dedicated infrastructure engineering required." },
            { range: "50+ GPU nodes", title: "AI Factory Planning", desc: "Multi-rack power, cooling, network fabric, staging, spares and phased deployment." },
            { range: "100+ GPU nodes", title: "Capacity Reservation", desc: "Facility capacity and deployment schedule confirmed before commercial commitment." },
        ],
    },
    faq: {
        title: "Frequently Asked Questions",
        items: [
            { q: "Does GDI own the data centers?", a: "GDI provides managed colocation through selected partner data-center facilities. This allows us to match the facility to the technical and commercial requirements of each project rather than limiting customers to one location." },
            { q: "Can I colocate only one server?", a: "Yes. GDI can support deployments ranging from individual 1U/2U systems to dedicated racks and large GPU clusters, subject to facility availability." },
            { q: "Can GDI host NVIDIA B200 or B300 systems?", a: "GDI can source suitable high-density colocation capacity and coordinate the deployment. Final acceptance depends on the exact server configuration and facility engineering validation, especially power and cooling requirements." },
            { q: "Why is GPU colocation more expensive than normal server colocation?", a: "High-density AI servers can consume many times more power per rack than standard enterprise servers. The facility must also support the corresponding cooling, electrical distribution and network requirements." },
            { q: "Can GDI receive and install my servers?", a: "Yes, hardware receiving, installation, rack-and-stack, cabling and commissioning support can be included in the project scope." },
            { q: "Can GDI provide remote hands?", a: "Yes. GDI can coordinate approved on-site tasks such as reboots, cable checks, visual inspections and component replacement. Scope and response conditions depend on the selected managed-service package and facility." },
            { q: "Can I use my own IP addresses or ASN?", a: "In many deployments this can be supported through appropriate network arrangements. GDI will confirm BGP, cross-connect and provider requirements during technical design." },
            { q: "Can GDI split my infrastructure across two data centers?", a: "Yes. GDI can design primary/DR or other multi-site configurations, subject to capacity and connectivity requirements." },
            { q: "Are calculator prices final?", a: "No. The calculator provides a planning estimate. Final pricing is confirmed after GDI validates actual equipment specifications, facility capacity, reserved power, connectivity and contract conditions." },
        ],
    },
    finalCta: {
        h2: "Tell Us What You Need to Deploy",
        copy: "Send us the server model and quantity. GDI will evaluate suitable data-center capacity in Jakarta and prepare a consolidated colocation and managed-service proposal.",
        primary: "Get Infrastructure Quote",
        secondary: "Talk to GDI",
        micro: "Standard servers • full racks • H100/H200 • B200/B300 • multi-site deployments",
    },
    serverOps: {
        title: "Managed Server Operations",
        intro: "Colocation keeps your hardware powered and connected. Managed Server Operations keeps the operating system, security, backups and applications on those servers healthy — without hiring your own on-call sysadmin.",
        boundary: "Separate from data-center remote hands (physical tasks at the facility) and from hardware warranty / OEM support. Operations plans are billed per server per month and can be added to any colocation estimate.",
        perServerMonth: "/ server / month",
        perNodeMonth: "/ GPU node / month",
        setup: "Onboarding",
        included: "What is included",
        hours: "admin hours / month",
        response: "response",
        coverage: { "24x7-monitoring": "24/7 monitoring, alerts", "business-hours": "Business hours (09:00–18:00 WIB)", "24x7": "24/7 incident response" },
        plans: {
            essential: {
                name: "Essential Monitoring", tagline: "Know before your users do.",
                items: ["24/7 uptime, CPU, RAM, disk and network monitoring", "Alerting to your team (email / WhatsApp / Telegram)", "Incident escalation to facility remote hands", "Monthly availability and health report", "No administrative work included"],
            },
            standard: {
                name: "Standard Managed OS", tagline: "Patched, hardened, backed up.",
                items: ["Everything in Essential", "Monthly OS patching in an agreed window (Linux / Windows)", "Security hardening: firewall, SSH / RDP, fail2ban, updates", "User and access management", "Backup job configuration and monitoring (storage separate)", "Log review and capacity notes", "Up to 4 admin hours / month, 4-business-hour response"],
            },
            advanced: {
                name: "Advanced 24/7 Managed", tagline: "Production servers that cannot wait until morning.",
                items: ["Everything in Standard", "24/7 incident response, 30-minute urgent SLA", "Emergency security patching outside the window", "Application stack support: web, database, containers", "Performance tuning and capacity planning", "Quarterly backup restore test and DR runbook", "Change management and monthly service review", "Up to 10 admin hours / month"],
            },
            gpu: {
                name: "GPU / AI Node Operations", tagline: "For H100, H200, B200 and B300 nodes.",
                items: ["24/7 node health: GPU, HBM, NVLink, thermals via DCGM", "Driver, CUDA, firmware and BMC lifecycle management", "Scheduler support: Slurm, Kubernetes, container runtime", "Hardware RMA coordination with NVIDIA / OEM", "Burn-in, benchmark baseline and regression checks", "Cluster network health checks (Ethernet / InfiniBand)", "Up to 12 engineer hours / node / month", "Volume pricing reviewed from 10 nodes"],
                note: "Excludes NVIDIA DGX Care / OEM support contracts, which remain with the customer or are passed through at cost.",
            },
        },
        addonsTitle: "Operations add-ons",
        addons: {
            extraHour: "Additional admin hour",
            backup: "Managed backup storage",
            backupUnit: "per 100 GB / month",
            backupTb: "per TB / month",
            hardware: "Hardware maintenance (parts + labour, next business day)",
            hardwareNote: "4-hour 24×7 hardware SLA: request quote",
            vuln: "Monthly vulnerability scan + report",
            dr: "DR restore test / drill",
            perEvent: "per event",
            licensing: "Windows Server / SQL Server licensing (SPLA) and OEM support contracts: quoted separately",
        },
        cta: "Add operations to my estimate",
        calc: {
            label: "Server operations",
            none: "No operations plan (colocation only)",
            hint: "OS-level management of your servers. GPU nodes use the GPU / AI Node Operations plan.",
            volumeReview: "Volume pricing for GPU operations is reviewed from 10 nodes.",
            resultRow: "Server operations",
            resultSetup: "Onboarding included in one-time deployment",
        },
    },
    eyebrows: { manages: "Managed layer", serverOps: "Server operations", why: "Multi-data-center model", categories: "Server profiles", racks: "Standard racks", ops: "Operations", process: "Timeline", reporting: "Visibility", multisite: "Multi-site", scale: "Scale", faq: "FAQ" },
    disclaimer: "Indicative prices only and subject to technical validation, facility availability and contract conditions. High-density GPU deployments require confirmation of power, cooling, rack and network capacity. Prices exclude applicable taxes and optional third-party connectivity/cross-connect charges unless specifically included in the final proposal.",
    lead: {
        title: "Request Final Quote",
        intro: "Your calculator estimate is attached automatically. GDI will review facility capacity, power and connectivity requirements before issuing the final infrastructure proposal.",
        snapshot: "Attached estimate",
        fields: {
            name: "Full name",
            company: "Company",
            email: "Work email",
            phone: "WhatsApp / phone",
            serverType: "Server type",
            quantity: "Quantity",
            contract: "Contract term",
            deploymentDate: "Preferred deployment date",
            currentLocation: "Server currently located in",
            needReceiving: "Need GDI to receive hardware?",
            connectivity: "Connectivity requirement",
            gpuFabric: "High-speed GPU fabric required?",
            siteMode: "Single site / DR site",
            notes: "Additional notes",
        },
        yes: "Yes",
        no: "No",
        notSure: "Not sure",
        technicalTitle: "Technical details (optional)",
        technical: {
            model: "Exact system model / OEM",
            systems: "Number of systems",
            powerPref: "AC PSU or DC busbar preference (if known)",
            targetDate: "Target deployment date",
            topology: "Expected cluster topology",
            infiniband: "InfiniBand required",
            ethernet: "Ethernet speed required",
            storage: "Storage platform",
            storageThroughput: "Storage throughput requirement",
            publicInternet: "Public Internet required",
            privateCircuit: "Private circuit required",
            asn: "Existing ASN / IP space",
            mgmtNetwork: "Remote management network",
            staging: "Need staging / burn-in",
            spares: "Need spare-parts storage",
            noc247: "Need 24/7 remote operations",
            drSite: "Need secondary site / DR",
        },
        submit: "Send Request",
        sending: "Sending…",
        success: "Thank you. GDI will review facility capacity, power and connectivity requirements before issuing the final infrastructure proposal.",
        error: "Could not send the request. Please try again or email info@gdiconsult.online.",
        required: "Please fill in all required fields.",
        privacy: "By sending this request you agree to be contacted by GDI about your infrastructure enquiry.",
        close: "Close",
    },
};

export type ColocationContent = typeof en;

const id: ColocationContent = {
    meta: {
        title: "Colocation Server Jakarta | Colocation GPU & NVIDIA B200/B300 | GDI Consult",
        description:
            "Colocation server terkelola di Jakarta untuk infrastruktur enterprise, GPU dan AI. GDI mengelola pemilihan fasilitas, ruang rak, daya, konektivitas, instalasi, remote hands, pelaporan serta deployment NVIDIA H100, H200, B200 dan B300.",
    },
    nav: "Data Center & Colocation",
    hero: {
        eyebrow: "Layanan Data Center Terkelola • Jakarta",
        h1: "Colocation Server Terkelola di Jakarta",
        p1: "Satu penyedia untuk ruang rak, daya, konektivitas, instalasi dan operasional server berkelanjutan di berbagai fasilitas data center di Jakarta.",
        p2: "Dari server enterprise 1U standar hingga infrastruktur high-density NVIDIA H100, H200, B200 dan B300, GDI memilih fasilitas yang sesuai dan mengelola deployment dari instalasi hingga laporan bulanan.",
        ctaPrimary: "Hitung Biaya Colocation",
        ctaSecondary: "Minta Penawaran Infrastruktur",
        micro1: "1 server → rak penuh → 100+ node GPU",
        micro2: "Harga indikatif tersedia seketika. Validasi teknis akhir diperlukan untuk deployment GPU high-density.",
        tagline: "Satu penyedia. Banyak data center. Satu titik tanggung jawab.",
    },
    trust: [
        { title: "Banyak Fasilitas", desc: "GDI dapat mengalokasikan infrastruktur di berbagai data center mitra." },
        { title: "Satu Titik Kontak", desc: "Satu tim GDI mengoordinasikan fasilitas, jaringan dan operasional di lokasi." },
        { title: "Perencanaan Siap GPU", desc: "Kebutuhan daya dan pendinginan dievaluasi sebelum deployment." },
        { title: "Pelaporan Operasional", desc: "Laporan infrastruktur, insiden dan layanan secara berkala untuk pelanggan." },
    ],
    manages: {
        title: "Lebih dari Sekadar Ruang Rak",
        intro: "Colocation menjadi rumit ketika pelanggan harus berkoordinasi terpisah dengan data center, penyedia jaringan, teknisi lokal dan vendor perangkat keras. GDI menyediakan satu lapisan terkelola untuk seluruh deployment.",
        cards: [
            { title: "Pemilihan Fasilitas", desc: "Kami mencocokkan profil server dengan fasilitas yang sesuai berdasarkan kapasitas rak, kepadatan daya, pendinginan, konektivitas, kebutuhan keamanan dan anggaran." },
            { title: "Alokasi Rak & Daya", desc: "GDI mereservasi unit rak, kapasitas daya, feed dan konfigurasi PDU yang dibutuhkan untuk perangkat yang dipilih." },
            { title: "Instalasi & Kabel", desc: "Penerimaan server, pemasangan di rak, sambungan daya, kabel jaringan, pelabelan dan pemeriksaan fisik awal dapat dikoordinasikan oleh GDI." },
            { title: "Konektivitas", desc: "Bandwidth internet, konektivitas domestik, bandwidth internasional, IP publik, BGP dan cross-connect dapat disertakan dalam deployment." },
            { title: "Remote Hands", desc: "Reboot fisik, pemeriksaan kabel, inspeksi visual, penggantian komponen dan tugas on-site lain yang disetujui dapat dikoordinasikan tanpa mengirim teknisi Anda ke Jakarta." },
            { title: "Monitoring & Insiden", desc: "GDI menjadi titik koordinasi operasional untuk insiden infrastruktur dan mengeskalasi masalah ke tim fasilitas atau jaringan yang tepat." },
            { title: "Logistik Perangkat", desc: "Opsional: penerimaan, kontrol inventaris, penanganan suku cadang, koordinasi RMA dan dukungan penggantian perangkat." },
            { title: "Pelaporan", desc: "Pelanggan dapat menerima laporan berkala mencakup aset, insiden, pemeliharaan, aktivitas layanan dan metrik infrastruktur yang tersedia." },
        ],
    },
    why: {
        title: "Fasilitas yang Tepat untuk Server yang Tepat",
        p1: "Tidak semua data center cocok untuk setiap beban kerja.",
        p2: "Server aplikasi 1U standar mungkin hanya membutuhkan beberapa ratus watt, sementara NVIDIA DGX B200 dapat membutuhkan hingga sekitar 14,3 kW dan DGX B300 sekitar 14,5 kW daya operasional, dengan kebutuhan perencanaan kepadatan rak yang jauh lebih tinggi.",
        p3: "Alih-alih memaksa setiap pelanggan ke satu fasilitas, GDI dapat memilih dari berbagai lokasi mitra dan mengalokasikan infrastruktur sesuai beban kerja sebenarnya.",
        examples: [
            { title: "Enterprise Standar", desc: "Prioritas: efisiensi biaya, konektivitas andal, kepadatan rak normal." },
            { title: "Business Critical", desc: "Prioritas: opsi daya/jaringan redundan, SLA lebih ketat, akses terkendali dan pelaporan." },
            { title: "AI / High Density", desc: "Prioritas: daya tinggi per rak, kemampuan pendinginan, desain kelistrikan, kedalaman/berat rak, jaringan kecepatan tinggi dan kapasitas ekspansi." },
        ],
    },
    categories: {
        title: "Kategori Server",
        intro: "Pilih profil yang paling mendekati perangkat Anda. Tidak perlu detail teknis rak yang persis — preset sudah membawa nilai default yang wajar, dan opsi Custom memungkinkan Anda memasukkan sendiri.",
        from: "Mulai",
        perMonth: "/ bulan",
        perServerMonth: "/ server / bulan",
        setup: "Biaya setup sekali bayar mulai",
        examples: "Contoh",
        configure: "Konfigurasi",
        validation: "Validasi fasilitas diperlukan",
        powerProfile: "profil daya",
        pricingPower: "daya untuk perhitungan",
        maxPower: "daya sistem maksimum",
        typicalPower: "daya tipikal",
        planningPower: "nilai perencanaan",
        rack: "Rak",
        presets: {
            "standard-1u": { desc: "Server komputasi 1U single/dual-socket untuk aplikasi, web dan beban kerja umum." },
            "standard-2u": { desc: "Server komputasi 2U dengan lebih banyak bay penyimpanan atau kartu ekspansi, dalam batas daya standar." },
            "storage-2u": { desc: "Appliance penyimpanan atau sistem padat CPU di atas batas daya standar. Dihitung dengan tambahan daya tereservasi." },
            "gpu-4u-l40s": { desc: "Server GPU PCIe untuk inferensi dan pelatihan skala menengah. Desain OEM bervariasi, jadi ini preset estimasi, bukan spesifikasi kelistrikan yang dijamin.", note: "Harga akhir bergantung pada PSU server sebenarnya dan profil daya terukur / tereservasi." },
            "dgx-h100": { desc: "Sistem 8U berpendingin udara dengan 8× GPU H100. Penempatan high-density, validasi teknis diperlukan." },
            "dgx-h200": { desc: "Chassis dan envelope daya yang sama dengan DGX H100 dengan 8× GPU H200." },
            "dgx-b200": { desc: "Infrastruktur NVIDIA B200 memerlukan rekayasa data center di luar colocation standar. GDI mengevaluasi tata letak rak, feed daya, kapasitas pendinginan, berat server, desain jaringan dan kapasitas ekspansi sebelum mengonfirmasi fasilitas." },
            "dgx-b300": { desc: "Untuk deployment B300, GDI memvalidasi desain kelistrikan, konfigurasi rak, profil pendinginan dan arsitektur jaringan bersama fasilitas terpilih sebelum instalasi." },
        },
        badges: { "popular-ai": "Populer AI", "blackwell-ultra": "Blackwell Ultra" },
        custom: { title: "Server Custom", desc: "Masukkan unit rak, daya, feed, kedalaman, berat dan port untuk sistem lain. Di atas 5 kW per server diklasifikasikan high density; di atas 10 kW diperlukan tinjauan teknis sebelum penawaran akhir." },
    },
    ai: {
        eyebrow: "Infrastruktur AI",
        h2: "Colocation untuk NVIDIA B200 & B300",
        p1: "Sistem kelas Blackwell tidak dapat diperlakukan seperti server rak standar. DGX B200 menempati 10U dan dapat membutuhkan hingga 14,3 kW. DGX B300 juga sistem 10U dan beroperasi di kelas sekitar 14,5 kW, dengan maksimum sistem 15 kW yang digunakan untuk perencanaan kapasitas.",
        p2: "Pada kepadatan ini, ruang rak yang tersedia hanya sebagian dari masalah. Fasilitas harus mampu mendukung desain kelistrikan, pendinginan, aliran udara, berat rak, arsitektur PDU atau busbar serta konektivitas jaringan kecepatan tinggi yang diperlukan.",
        p3: "GDI mengevaluasi kebutuhan ini di fasilitas mitra yang sesuai sebelum mengonfirmasi deployment.",
        b200: ["10U", "14,3 kW maks", "8× GPU B200", "Validasi high-density diperlukan"],
        b300: ["10U", "kelas operasi ~14,5 kW", "nilai perencanaan 15 kW", "8× GPU B300"],
        rackPlanning: "Perencanaan rak",
        defaultRack: "Default: 2 sistem per rak",
        specializedRack: "Khusus: 4 sistem per rak — memerlukan fasilitas high-density khusus, tergantung persetujuan teknis.",
        ctaPrimary: "Rencanakan Deployment B200 / B300",
        ctaSecondary: "Hitung 1–200 Server",
    },
    calculator: {
        title: "Estimasi Biaya Colocation Anda",
        intro: "Pilih tipe dan jumlah server. Kami akan mengestimasi ruang rak, daya tereservasi dan biaya colocation bulanan. Estimasi GPU high-density bersifat indikatif dan memerlukan validasi fasilitas akhir.",
        configure: "Konfigurasi",
        estimate: "Estimasi Anda",
        serverType: "Tipe server",
        quantity: "Jumlah",
        quantityHint: "1–200 server",
        moreThanMax: "Butuh lebih dari 200? Minta rencana infrastruktur khusus.",
        contract: "Kontrak",
        months: "bulan",
        month: "bulan",
        longTerm: "Harga jangka panjang dan volume dapat tersedia setelah konfirmasi fasilitas.",
        connectivity: "Konektivitas",
        bandwidth: {
            basic: "Konektivitas bersama / dasar",
            domestic: "Domestik",
            international: "Internasional",
            dedicated: "dedicated",
            custom: "Custom / BGP / Cross-connect",
        },
        fabric: "Saya membutuhkan jaringan klaster GPU kecepatan tinggi / InfiniBand",
        fabricNote: "Penawaran jaringan khusus diperlukan",
        site: "Redundansi / multi-site",
        siteOptions: { single: "Satu fasilitas", dr: "Fasilitas utama + sekunder / DR", recommend: "Belum yakin — biarkan GDI merekomendasikan" },
        drScope: "Apa yang perlu diduplikasi?",
        drScopeOptions: { all: "Semua server", count: "Sejumlah server tertentu", custom: "Hanya jaringan / custom" },
        drCount: "Server di situs DR",
        drCustomNote: "Desain DR khusus — dihitung dalam proposal akhir.",
        drRecommendNote: "GDI akan mengusulkan desain satu situs atau multi-site sesuai kebutuhan Anda.",
        serviceLevel: "Tingkat layanan",
        service: {
            core: { name: "GDI Core Management", price: "Termasuk", items: ["Koordinasi fasilitas", "Koordinasi deployment dasar", "Eskalasi insiden", "Laporan layanan bulanan"] },
            remote: { name: "Managed Remote Operations", price: "+ Rp 2.400.000 / bulan / deployment", items: ["Koordinasi prioritas", "Alokasi remote-hands sesuai kesepakatan", "Koordinasi pemeliharaan", "Laporan bulanan diperluas"] },
            enterprise: { name: "Enterprise NOC / Mission Critical", price: "Penawaran khusus", items: ["Dukungan operasional 24/7 dengan cakupan terpisah", "Klaster GPU, multi-rak dan beban kerja teregulasi"] },
        },
        customFields: {
            rackU: "Unit rak (U)",
            powerWatts: "Daya perkiraan / maksimum (W)",
            psuCount: "Jumlah PSU",
            dualFeed: "Dual power feed (A+B)",
            depthMm: "Kedalaman server (mm)",
            weightKg: "Berat (kg)",
            ports: "Port jaringan yang dibutuhkan",
            specialCooling: "Kebutuhan pendinginan khusus",
            notes: "Nomor model / catatan",
        },
        powerOverride: "Daya aktual per server (W, opsional)",
        powerOverrideHint: "Kosongkan untuk menggunakan profil daya yang termasuk.",
        result: {
            monthly: "Estimasi Colocation Bulanan",
            perMonth: "/ bulan",
            profile: "Profil server",
            quantity: "Jumlah",
            rackSpace: "Ruang rak",
            power: "Daya server tereservasi",
            racks: "Estimasi rak",
            facility: "Rekomendasi deployment",
            setup: "Estimasi biaya deployment sekali bayar",
            connectivity: "Konektivitas",
            service: "Layanan terkelola",
            contractTotal: "Estimasi berulang untuk",
            finalQuote: "Penawaran akhir",
            validation: "Validasi teknis fasilitas diperlukan",
            standardQuote: "Dikonfirmasi setelah pengecekan ketersediaan fasilitas",
            quoteRequired: "Perlu penawaran",
            included: "Termasuk",
            drSuffix: "termasuk situs DR",
            engineering: "Tinjauan teknis diperlukan sebelum penawaran akhir.",
        },
        facility: {
            standard: "Fasilitas Enterprise Standar",
            "standard-extended": "Fasilitas standar dengan daya diperluas",
            "high-density-gpu": "Fasilitas GPU High-Density",
            "high-density-ai": "Fasilitas AI High-Density",
        },
        tiers: {
            enterprise: { title: "Infrastruktur Enterprise", desc: "Deployment Anda mungkin memenuhi syarat untuk rak khusus, blok daya tereservasi dan harga fasilitas yang dinegosiasikan. GDI akan memvalidasi arsitektur dan meminta kapasitas dari fasilitas mitra yang sesuai sebelum menerbitkan proposal akhir." },
            "large-cluster": { title: "Klaster AI Besar", desc: "Rekayasa infrastruktur khusus diperlukan." },
            "ai-factory": { title: "Perencanaan AI Factory / Klaster Besar", desc: "GDI akan mengevaluasi daya multi-rak, pendinginan, fabric jaringan, staging, suku cadang dan deployment bertahap." },
            "capacity-reservation": { title: "Reservasi Kapasitas Enterprise", desc: "Kapasitas fasilitas dan jadwal deployment harus dikonfirmasi sebelum komitmen komersial. Kapasitas multi-megawatt memerlukan reservasi kapasitas fasilitas formal." },
        },
        planningNote: "Ini adalah estimasi perencanaan, bukan penawaran yang mengikat.",
        rackViz: { perRack: "Beban server per rak", standard: "standar", highDensity: "high density", serversPerRack: "server / rak" },
        ctaQuote: "Dapatkan Penawaran Akhir",
        ctaEnterprise: "Minta Penawaran Enterprise",
        ctaSend: "Kirim Estimasi ke GDI",
        tooltips: {
            u: "Unit rak: 1U = 44,45 mm ruang vertikal rak.",
            kw: "Kapasitas listrik yang direservasi untuk server, bukan konsumsi rata-rata.",
            remoteHands: "Tugas di lokasi yang dilakukan staf fasilitas atas nama Anda.",
            bgp: "Border Gateway Protocol — mengumumkan ruang IP / ASN Anda sendiri.",
            crossConnect: "Kabel fisik antara rak Anda dan pihak lain di dalam fasilitas.",
        },
    },
    rackPricing: {
        title: "Colocation Standar — Harga Indikatif",
        items: {
            "1u": { name: "Server 1U", lines: ["Profil hingga ~450 W", "Koordinasi GDI dasar", "1 server"], cta: "Konfigurasi 1U" },
            "2u": { name: "Server 2U", lines: ["Profil hingga ~500 W", "Koordinasi GDI dasar", "1 server"], cta: "Konfigurasi 2U" },
            quarter: { name: "Quarter Rack", lines: ["Kelas sekitar 10U", "Alokasi daya tergantung fasilitas"] },
            half: { name: "Half Rack", lines: ["Kelas sekitar 20–22U", "Alokasi daya tergantung fasilitas"] },
            full: { name: "Full Rack", lines: ["Kelas sekitar 42–45U", "Hanya daya kepadatan standar"] },
        },
        footnote: "Daya GPU high-density dihitung terpisah dan tidak boleh diestimasi dari harga full rack standar.",
        addonsTitle: "Tambahan",
        addons: [
            "Tambahan 100 W (server standar): Rp 420.000 / bulan",
            "IPv4 tambahan: mulai Rp 36.000 / bulan",
            "Port LAN tambahan: Rp 180.000 / bulan",
            "Soket daya standar tambahan: Rp 180.000 / bulan",
            "Bantuan instalasi OS: Rp 420.000 / kejadian",
            "Cross-connect, BGP, private circuit, IX, dark fiber, cloud connect, AI fabric: minta penawaran",
        ],
        requestQuote: "Minta penawaran",
    },
    serviceLevels: {
        title: "Tingkat Layanan Terkelola",
        intro: "Setiap tingkat mendefinisikan batas tanggung jawab antara GDI, fasilitas dan tim Anda.",
        core: { name: "GDI Core Management", badge: "Default", price: "Termasuk dalam estimasi dasar", items: ["Pemilihan dan koordinasi fasilitas", "Koordinasi deployment", "Registrasi aset", "Eskalasi insiden", "Koordinasi pemeliharaan", "Laporan layanan bulanan dasar", "Satu kontak komersial GDI"] },
        remote: { name: "Managed Remote Operations", badge: "Opsional", price: "Mulai Rp 2.400.000 / bulan / deployment", items: ["Semua yang ada di Core", "Koordinasi operasional prioritas", "Alokasi remote-hands sesuai kontrak", "Pemeriksaan fisik dan intervensi yang disetujui", "Koordinasi suku cadang / RMA", "Laporan bulanan diperluas"] },
        enterprise: { name: "Enterprise NOC", badge: "Custom", price: "Penawaran khusus", items: ["Klaster GPU dan lingkungan multi-rak", "Beban kerja teregulasi dan business-critical", "Kebutuhan eskalasi 24/7", "Respons insiden khusus", "Infrastruktur multi-site"], cta: "Rancang SLA Enterprise" },
    },
    process: {
        title: "Proses Deployment",
        steps: [
            { title: "Kebutuhan", desc: "Kami mengumpulkan model server, jumlah, daya, konektivitas, tanggal deployment dan kebutuhan operasional." },
            { title: "Pencocokan Fasilitas", desc: "GDI mengevaluasi fasilitas mitra yang sesuai dan kapasitas tersedia di Jakarta / Jabodetabek." },
            { title: "Validasi Teknis", desc: "Kebutuhan rak, kelistrikan, pendinginan, jaringan, berat dan akses diperiksa sebelum komitmen." },
            { title: "Proposal Komersial", desc: "GDI menerbitkan satu proposal terkonsolidasi untuk infrastruktur dan layanan terkelola yang dipilih." },
            { title: "Deployment", desc: "Penerimaan perangkat, pemasangan rak, daya, kabel dan konektivitas dikoordinasikan sesuai cakupan yang disetujui." },
            { title: "Operasional", desc: "GDI mengelola koordinasi berkelanjutan, insiden, remote hands, pelaporan dan ekspansi di masa depan." },
        ],
    },
    reporting: {
        title: "Ketahui Apa yang Terjadi pada Infrastruktur Anda",
        copy: "GDI dapat mengonsolidasikan informasi operasional ke dalam laporan infrastruktur berkala, memberi manajemen satu pandangan atas aset yang di-deploy, aktivitas layanan dan insiden di lingkungan data center yang dipilih.",
        exampleTitle: "Contoh isi laporan",
        items: ["Referensi pelanggan / proyek dan fasilitas", "Inventaris aset, lokasi rak / posisi U bila diizinkan kontrak", "Daya teralokasi dan metrik daya tersedia", "Ringkasan bandwidth / trafik", "Insiden dibuka / ditutup, downtime atau kejadian SLA yang dilaporkan fasilitas", "Pemeliharaan terjadwal dan aktivitas remote-hands", "Perubahan perangkat dan penggunaan suku cadang", "Kejadian akses", "Risiko terbuka, tindakan yang direkomendasikan, catatan kapasitas / ekspansi"],
        note: "Metrik disertakan bila data tersedia dari fasilitas yang dipilih.",
    },
    multisite: {
        title: "Satu Kontrak GDI. Banyak Fasilitas.",
        copy: "Bagi pelanggan yang tidak ingin seluruh infrastruktur berada di satu lokasi, GDI dapat merancang deployment di beberapa data center mitra terpisah.",
        useCases: ["Utama + DR", "Produksi + cadangan", "Active + standby", "Diversitas jaringan", "Migrasi bertahap", "Pembagian kapasitas", "Komputasi AI di situs high-density + manajemen/penyimpanan di situs lain"],
        disclaimer: "Pemisahan geografis, latensi, konektivitas dan arsitektur failover sebenarnya bergantung pada fasilitas yang dipilih dan kebutuhan pelanggan.",
    },
    enterprise: {
        title: "Deployment Enterprise",
        copy: "Mulai dari sepuluh node GPU, GDI memperlakukan proyek sebagai infrastruktur khusus: rak dan blok daya tereservasi, pengiriman bertahap, staging dan suku cadang. Kalkulator menandai tingkatnya secara otomatis.",
        tiers: [
            { range: "10+ node GPU", title: "Infrastruktur Enterprise", desc: "Rak khusus, blok daya tereservasi dan harga fasilitas yang dinegosiasikan setelah permintaan kapasitas." },
            { range: "20+ node GPU", title: "Klaster AI Besar", desc: "Rekayasa infrastruktur khusus diperlukan." },
            { range: "50+ node GPU", title: "Perencanaan AI Factory", desc: "Daya multi-rak, pendinginan, fabric jaringan, staging, suku cadang dan deployment bertahap." },
            { range: "100+ node GPU", title: "Reservasi Kapasitas", desc: "Kapasitas fasilitas dan jadwal deployment dikonfirmasi sebelum komitmen komersial." },
        ],
    },
    faq: {
        title: "Pertanyaan yang Sering Diajukan",
        items: [
            { q: "Apakah GDI memiliki data center sendiri?", a: "GDI menyediakan colocation terkelola melalui fasilitas data center mitra terpilih. Ini memungkinkan kami mencocokkan fasilitas dengan kebutuhan teknis dan komersial setiap proyek, bukan membatasi pelanggan pada satu lokasi." },
            { q: "Bisakah saya colocation hanya satu server?", a: "Ya. GDI dapat mendukung deployment mulai dari sistem 1U/2U tunggal hingga rak khusus dan klaster GPU besar, tergantung ketersediaan fasilitas." },
            { q: "Bisakah GDI menampung sistem NVIDIA B200 atau B300?", a: "GDI dapat mencari kapasitas colocation high-density yang sesuai dan mengoordinasikan deployment. Penerimaan akhir bergantung pada konfigurasi server yang persis dan validasi teknis fasilitas, terutama kebutuhan daya dan pendinginan." },
            { q: "Mengapa colocation GPU lebih mahal daripada colocation server biasa?", a: "Server AI high-density dapat mengonsumsi daya per rak berkali-kali lipat dibanding server enterprise standar. Fasilitas juga harus mendukung pendinginan, distribusi listrik dan kebutuhan jaringan yang sesuai." },
            { q: "Bisakah GDI menerima dan memasang server saya?", a: "Ya, penerimaan perangkat, instalasi, rack-and-stack, pengkabelan dan dukungan commissioning dapat disertakan dalam cakupan proyek." },
            { q: "Apakah GDI menyediakan remote hands?", a: "Ya. GDI dapat mengoordinasikan tugas on-site yang disetujui seperti reboot, pemeriksaan kabel, inspeksi visual dan penggantian komponen. Cakupan dan ketentuan respons bergantung pada paket layanan terkelola dan fasilitas yang dipilih." },
            { q: "Bisakah saya menggunakan alamat IP atau ASN sendiri?", a: "Dalam banyak deployment hal ini dapat didukung melalui pengaturan jaringan yang sesuai. GDI akan mengonfirmasi kebutuhan BGP, cross-connect dan penyedia saat desain teknis." },
            { q: "Bisakah GDI membagi infrastruktur saya di dua data center?", a: "Ya. GDI dapat merancang konfigurasi utama/DR atau multi-site lainnya, tergantung kapasitas dan kebutuhan konektivitas." },
            { q: "Apakah harga kalkulator bersifat final?", a: "Tidak. Kalkulator memberikan estimasi perencanaan. Harga akhir dikonfirmasi setelah GDI memvalidasi spesifikasi perangkat sebenarnya, kapasitas fasilitas, daya tereservasi, konektivitas dan ketentuan kontrak." },
        ],
    },
    finalCta: {
        h2: "Ceritakan Apa yang Perlu Anda Deploy",
        copy: "Kirimkan model dan jumlah server. GDI akan mengevaluasi kapasitas data center yang sesuai di Jakarta dan menyiapkan proposal colocation dan layanan terkelola terkonsolidasi.",
        primary: "Dapatkan Penawaran Infrastruktur",
        secondary: "Hubungi GDI",
        micro: "Server standar • full rack • H100/H200 • B200/B300 • deployment multi-site",
    },
    serverOps: {
        title: "Operasional Server Terkelola",
        intro: "Colocation menjaga perangkat keras Anda tetap berdaya dan terhubung. Operasional Server Terkelola menjaga sistem operasi, keamanan, backup dan aplikasi di server tersebut tetap sehat — tanpa perlu merekrut sysadmin on-call sendiri.",
        boundary: "Terpisah dari remote hands data center (tugas fisik di fasilitas) dan dari garansi perangkat keras / dukungan OEM. Paket operasional ditagih per server per bulan dan dapat ditambahkan ke estimasi colocation mana pun.",
        perServerMonth: "/ server / bulan",
        perNodeMonth: "/ node GPU / bulan",
        setup: "Onboarding",
        included: "Yang termasuk",
        hours: "jam admin / bulan",
        response: "respons",
        coverage: { "24x7-monitoring": "Monitoring 24/7, notifikasi", "business-hours": "Jam kerja (09.00–18.00 WIB)", "24x7": "Respons insiden 24/7" },
        plans: {
            essential: {
                name: "Essential Monitoring", tagline: "Tahu lebih dulu sebelum pengguna Anda.",
                items: ["Monitoring uptime, CPU, RAM, disk dan jaringan 24/7", "Notifikasi ke tim Anda (email / WhatsApp / Telegram)", "Eskalasi insiden ke remote hands fasilitas", "Laporan ketersediaan dan kesehatan bulanan", "Tidak termasuk pekerjaan administrasi"],
            },
            standard: {
                name: "Standard Managed OS", tagline: "Ter-patch, diperkuat, ter-backup.",
                items: ["Semua yang ada di Essential", "Patching OS bulanan pada jendela yang disepakati (Linux / Windows)", "Hardening keamanan: firewall, SSH / RDP, fail2ban, update", "Manajemen pengguna dan akses", "Konfigurasi dan monitoring job backup (penyimpanan terpisah)", "Tinjauan log dan catatan kapasitas", "Hingga 4 jam admin / bulan, respons 4 jam kerja"],
            },
            advanced: {
                name: "Advanced 24/7 Managed", tagline: "Server produksi yang tidak bisa menunggu pagi.",
                items: ["Semua yang ada di Standard", "Respons insiden 24/7, SLA darurat 30 menit", "Patching keamanan darurat di luar jendela", "Dukungan stack aplikasi: web, database, container", "Tuning performa dan perencanaan kapasitas", "Uji restore backup triwulanan dan runbook DR", "Manajemen perubahan dan tinjauan layanan bulanan", "Hingga 10 jam admin / bulan"],
            },
            gpu: {
                name: "GPU / AI Node Operations", tagline: "Untuk node H100, H200, B200 dan B300.",
                items: ["Kesehatan node 24/7: GPU, HBM, NVLink, termal via DCGM", "Manajemen siklus hidup driver, CUDA, firmware dan BMC", "Dukungan scheduler: Slurm, Kubernetes, container runtime", "Koordinasi RMA perangkat keras dengan NVIDIA / OEM", "Burn-in, baseline benchmark dan pemeriksaan regresi", "Pemeriksaan kesehatan jaringan klaster (Ethernet / InfiniBand)", "Hingga 12 jam engineer / node / bulan", "Harga volume ditinjau mulai 10 node"],
                note: "Tidak termasuk NVIDIA DGX Care / kontrak dukungan OEM, yang tetap di pelanggan atau diteruskan sesuai biaya.",
            },
        },
        addonsTitle: "Tambahan operasional",
        addons: {
            extraHour: "Jam admin tambahan",
            backup: "Penyimpanan backup terkelola",
            backupUnit: "per 100 GB / bulan",
            backupTb: "per TB / bulan",
            hardware: "Pemeliharaan perangkat keras (suku cadang + tenaga, hari kerja berikutnya)",
            hardwareNote: "SLA perangkat keras 4 jam 24×7: minta penawaran",
            vuln: "Pemindaian kerentanan bulanan + laporan",
            dr: "Uji restore DR / simulasi",
            perEvent: "per kejadian",
            licensing: "Lisensi Windows Server / SQL Server (SPLA) dan kontrak dukungan OEM: ditawarkan terpisah",
        },
        cta: "Tambahkan operasional ke estimasi saya",
        calc: {
            label: "Operasional server",
            none: "Tanpa paket operasional (hanya colocation)",
            hint: "Pengelolaan server Anda di tingkat OS. Node GPU menggunakan paket GPU / AI Node Operations.",
            volumeReview: "Harga volume untuk operasional GPU ditinjau mulai 10 node.",
            resultRow: "Operasional server",
            resultSetup: "Onboarding termasuk dalam biaya deployment sekali bayar",
        },
    },
    eyebrows: { manages: "Lapisan terkelola", serverOps: "Operasional server", why: "Model multi-data-center", categories: "Profil server", racks: "Rak standar", ops: "Operasional", process: "Alur", reporting: "Visibilitas", multisite: "Multi-site", scale: "Skala", faq: "FAQ" },
    disclaimer: "Harga bersifat indikatif dan tunduk pada validasi teknis, ketersediaan fasilitas dan ketentuan kontrak. Deployment GPU high-density memerlukan konfirmasi kapasitas daya, pendinginan, rak dan jaringan. Harga belum termasuk pajak yang berlaku dan biaya konektivitas/cross-connect pihak ketiga opsional kecuali secara khusus disertakan dalam proposal akhir.",
    lead: {
        title: "Minta Penawaran Akhir",
        intro: "Estimasi kalkulator Anda dilampirkan otomatis. GDI akan meninjau kapasitas fasilitas, daya dan kebutuhan konektivitas sebelum menerbitkan proposal infrastruktur akhir.",
        snapshot: "Estimasi terlampir",
        fields: {
            name: "Nama lengkap",
            company: "Perusahaan",
            email: "Email kerja",
            phone: "WhatsApp / telepon",
            serverType: "Tipe server",
            quantity: "Jumlah",
            contract: "Jangka kontrak",
            deploymentDate: "Tanggal deployment yang diinginkan",
            currentLocation: "Lokasi server saat ini",
            needReceiving: "Perlu GDI menerima perangkat?",
            connectivity: "Kebutuhan konektivitas",
            gpuFabric: "Perlu fabric GPU kecepatan tinggi?",
            siteMode: "Satu situs / situs DR",
            notes: "Catatan tambahan",
        },
        yes: "Ya",
        no: "Tidak",
        notSure: "Belum yakin",
        technicalTitle: "Detail teknis (opsional)",
        technical: {
            model: "Model sistem / OEM yang persis",
            systems: "Jumlah sistem",
            powerPref: "Preferensi PSU AC atau busbar DC (jika diketahui)",
            targetDate: "Target tanggal deployment",
            topology: "Topologi klaster yang diharapkan",
            infiniband: "InfiniBand diperlukan",
            ethernet: "Kecepatan Ethernet yang diperlukan",
            storage: "Platform penyimpanan",
            storageThroughput: "Kebutuhan throughput penyimpanan",
            publicInternet: "Internet publik diperlukan",
            privateCircuit: "Private circuit diperlukan",
            asn: "ASN / ruang IP yang ada",
            mgmtNetwork: "Jaringan manajemen jarak jauh",
            staging: "Perlu staging / burn-in",
            spares: "Perlu penyimpanan suku cadang",
            noc247: "Perlu operasional jarak jauh 24/7",
            drSite: "Perlu situs sekunder / DR",
        },
        submit: "Kirim Permintaan",
        sending: "Mengirim…",
        success: "Terima kasih. GDI akan meninjau kapasitas fasilitas, daya dan kebutuhan konektivitas sebelum menerbitkan proposal infrastruktur akhir.",
        error: "Permintaan tidak dapat dikirim. Silakan coba lagi atau email info@gdiconsult.online.",
        required: "Mohon lengkapi semua kolom wajib.",
        privacy: "Dengan mengirim permintaan ini Anda setuju dihubungi GDI terkait pertanyaan infrastruktur Anda.",
        close: "Tutup",
    },
};

export const colocationContent = { en, id } as const;
export type Lang = keyof typeof colocationContent;
