// Public copy for the AI services page (/products). EN / ID. Numbers live in ./config.ts.
import type { PackageId } from "./config";

export interface PackageCopy {
    tagline: string;
    forWho: string;
    problem: string;
    whatWeDo: string[];
    deliverables: string[];
    timeline: Array<{ when: string; what: string }>;
    youProvide: string[];
    notIncluded: string[];
    outcome: string;
}

const en = {
    meta: {
        title: "AI Services & Packages | Fixed Scope, Fixed Price | GDI Consult",
        description: "AI readiness sprint, automation pilot, automation program and private AI assistant — fixed-scope AI services for businesses in Indonesia and worldwide, delivered by Global Digital Informasi.",
    },
    nav: "AI Services",
    hero: {
        eyebrow: "AI Services • Fixed Scope • Fixed Price",
        h1: "AI services that ship in weeks, not quarters",
        p1: "Four packaged engagements with a defined scope, a fixed price and a delivery date — from a 7-day readiness sprint to a private AI assistant on your company data.",
        p2: "Every package is delivered by the same GDI team that runs your infrastructure: you get working software, documentation and trained people, not a slide deck.",
        ctaPrimary: "Compare packages",
        ctaSecondary: "Find my package",
        micro: "Bank transfer • kickoff within 2–3 working days • code and data stay yours",
    },
    trust: [
        { title: "Fixed scope, fixed price", desc: "You know what you get and what it costs before you pay. Changes are quoted, never surprised." },
        { title: "Working software", desc: "Pilots and programs end with automations running inside your own accounts and systems." },
        { title: "Your data, your code", desc: "Source code, prompts, workflows and data belong to you. NDA on request." },
        { title: "Software + infrastructure", desc: "Run models on our cloud, yours, or on your own GPU servers in GDI managed colocation." },
    ],
    packagesSection: {
        eyebrow: "Packages",
        title: "Pick the engagement that matches where you are",
        intro: "Start with the sprint if you are unsure where AI pays off. Go straight to a pilot if you already have one painful process. Programs and assistants are for teams ready to change how a department works.",
        from: "Fixed price",
        exclTax: "excl. applicable taxes",
        duration: "Delivery",
        workingDays: "working days",
        weeks: "weeks",
        buy: "Order this package",
        details: "See full scope",
        discuss: "Ask a question",
        featured: "Most chosen starting point",
        nextStep: "Natural next step",
    },
    packages: {
        "start-ai": {
            tagline: "Know where AI pays off in your company — in 7 working days.",
            forWho: "Companies with 10–500 people that have not started with AI, or started with scattered tools nobody uses.",
            problem: "You know AI could help, but not where, in which order, or what it would cost. Buying tools before answering that usually ends in unused licences.",
            whatWeDo: [
                "Interviews with owners of 1–2 departments (up to 4 sessions) and a map of their key processes",
                "Audit of current tools, data sources and integrations: what can be connected, what cannot",
                "4–6 concrete AI / automation use cases, each scored by expected saving, effort and risk",
                "6-month roadmap: what to build first, what to buy, what to postpone",
                "Walkthrough session with management and written answers to follow-up questions",
            ],
            deliverables: [
                "AI readiness report (PDF, 15–25 pages) with process map and tool audit",
                "Use-case backlog with ROI logic and effort estimate per case",
                "6-month implementation roadmap with budget ranges",
                "60-minute walkthrough session (online), recording included",
            ],
            timeline: [
                { when: "Day 1", what: "Kickoff, access to documents and tools, interview schedule" },
                { when: "Days 2–4", what: "Interviews, process mapping, tool and data audit" },
                { when: "Days 5–6", what: "Use-case scoring, roadmap, budget ranges" },
                { when: "Day 7", what: "Report delivery and walkthrough with management" },
            ],
            youProvide: ["2–4 hours of stakeholder time across the week", "Sample documents and read-only access to the tools you use", "One decision-maker for the walkthrough"],
            notIncluded: ["Implementation of any use case (that is the Automation Pilot)", "Software licences or API costs"],
            outcome: "A prioritised, costed plan your team can act on — and a pilot brief ready to start the next week.",
        },
        "middle-scale": {
            tagline: "One automation, built and running inside your workflow in 3 weeks.",
            forWho: "Teams with one clearly painful, repetitive process: document intake, lead qualification, order or ticket handling, weekly reporting, customer replies.",
            problem: "The process eats hours every day and everyone knows it, but nobody has time to automate it properly and keep it running.",
            whatWeDo: [
                "Scoping session (or your Readiness Sprint roadmap) to fix the process, inputs, outputs and success metric",
                "Design and build of one AI / automation workflow with up to 2 integrations (e.g. Gmail, Google Sheets, WhatsApp, CRM, accounting)",
                "Testing on your real data with the process owner, error handling and notifications",
                "Rollout to the team, one training session, user guide",
                "30 days of bug-fix support after go-live",
            ],
            deliverables: [
                "Working automation deployed in your accounts (n8n / Make / custom code — your choice)",
                "Up to 2 system integrations with monitoring and error alerts",
                "User guide and technical handover documentation",
                "90-minute training session for up to 5 users",
                "30-day support window with a named engineer",
            ],
            timeline: [
                { when: "Week 1", what: "Scoping, process design, access to systems, test data" },
                { when: "Week 2", what: "Build, integration, testing on real data with the process owner" },
                { when: "Week 3", what: "Rollout, training, documentation, handover" },
            ],
            youProvide: ["A process owner available ~2 hours per week", "Access to the systems the workflow touches", "Sample data for testing"],
            notIncluded: ["Third-party subscriptions (LLM API, automation platform, WhatsApp Business API)", "More than 2 integrations (quoted per integration)"],
            outcome: "A measurable process running without manual handoffs — and the numbers to decide what to automate next.",
        },
        "automation-platform": {
            tagline: "Up to three connected automations for one department, integrated with CRM, ERP and your tools.",
            forWho: "Operations, sales, finance or customer-service teams with several manual handoffs — or companies after a successful pilot.",
            problem: "Single automations help, but the real cost sits between systems: re-typing data, chasing approvals, building the same report in three tools.",
            whatWeDo: [
                "Process mapping of one department: handoffs, owners, systems, volumes",
                "Architecture for up to 3 connected workflows and up to 5 integrations (CRM, ERP, Google Workspace, Meta, WhatsApp, accounting, internal databases)",
                "Build, staged rollout and user acceptance testing with your team",
                "Central dashboard: runs, errors, volumes, time saved; role-based access",
                "Runbook, documentation, two training sessions and 30 days of support",
            ],
            deliverables: [
                "3 production automations with shared integration layer",
                "Up to 5 system integrations with monitoring and alerting",
                "Operations dashboard and monthly KPI baseline vs. after-measurement",
                "Runbook, architecture and handover documentation",
                "2 training sessions (users and internal admin)",
                "30-day support window",
            ],
            timeline: [
                { when: "Weeks 1–2", what: "Process mapping, architecture, integration access" },
                { when: "Weeks 3–5", what: "Build and internal testing, weekly demos" },
                { when: "Week 6", what: "User acceptance testing with your team" },
                { when: "Weeks 7–8", what: "Rollout, training, measurement, handover" },
            ],
            youProvide: ["A department lead and one power user, ~2–3 hours per week", "Access to systems and API credentials", "Sign-off on the process map in week 2"],
            notIncluded: ["Licences, hosting and API usage", "Custom ML model training (see custom development)", "More than 5 integrations (quoted per integration)"],
            outcome: "A department where data moves between systems by itself, with a dashboard that shows the hours saved every month.",
        },
        "ent-assistant": {
            tagline: "A private AI assistant that answers from your documents, policies and product data — for one department, in one channel.",
            forWho: "Customer support, sales, HR, legal or internal knowledge teams with document bases, policies, catalogues or manuals that people keep asking about.",
            problem: "Answers exist somewhere in PDFs, drives and chat history, but finding them takes minutes every time and the quality depends on who is on shift.",
            whatWeDo: [
                "Discovery: use cases, answer policies, what the assistant must never do",
                "Knowledge base pipeline (retrieval-augmented generation) from your documents — up to 500 documents / 5,000 pages, with scheduled updates",
                "Assistant in one channel of your choice: web widget, WhatsApp, Telegram, Slack or Microsoft Teams",
                "Role-based access, guardrails, source citations, escalation to a human",
                "Analytics panel: questions, answer quality, gaps in the knowledge base",
                "Pilot with the department, tuning, usage guidelines, training, 30 days of tuning after rollout",
            ],
            deliverables: [
                "Assistant live in 1 channel for 1 department",
                "Knowledge base pipeline with update schedule and access control",
                "Admin panel with analytics and conversation review",
                "Usage guidelines and answer-policy document",
                "2 training sessions (users and content owners)",
                "30-day tuning and support window",
            ],
            timeline: [
                { when: "Week 1", what: "Discovery, document collection, answer policies" },
                { when: "Weeks 2–3", what: "Knowledge pipeline, assistant build, channel integration" },
                { when: "Week 4", what: "Pilot with the department, review of real conversations" },
                { when: "Weeks 5–6", what: "Tuning, rollout, training, handover" },
            ],
            youProvide: ["Content owners who can confirm which documents are current", "A pilot group of 5–15 users", "Channel account (e.g. WhatsApp Business) if not using the web widget"],
            notIncluded: ["LLM API usage and hosting (or run it on your own GPU servers in GDI colocation)", "Additional channels or departments (quoted)", "Fine-tuning of custom models"],
            outcome: "Consistent, cited answers in seconds, an audit trail of every conversation, and a knowledge base that finally has an owner.",
        },
    } as Record<PackageId, PackageCopy>,
    compare: {
        eyebrow: "Compare",
        title: "Four packages side by side",
        rows: {
            duration: "Delivery time",
            yourTime: "Your team's time",
            result: "What you get",
            integrations: "Integrations included",
            training: "Training sessions",
            support: "Support after delivery",
            price: "Fixed price",
        },
        results: {
            "start-ai": "Report, use-case backlog, 6-month roadmap",
            "middle-scale": "1 automation live in your workflow",
            "automation-platform": "3 connected automations + dashboard",
            "ent-assistant": "AI assistant on your documents, 1 channel",
        } as Record<PackageId, string>,
        hours: "hours",
        days: "days",
        none: "—",
    },
    finder: {
        eyebrow: "Not sure?",
        title: "Find your package in three questions",
        q1: "Where is your company with AI today?",
        q1Options: {
            unsure: "We have not started, or we are not sure where it would pay off",
            "one-process": "We have one clear process that eats too much time",
            department: "A whole department runs on manual handoffs between systems",
            knowledge: "People keep asking questions that are answered somewhere in our documents",
        },
        q2: "How many systems would need to be connected?",
        q2Options: { "0-1": "None or one", "2": "Two", "3-5": "Three to five", "not-sure": "Not sure" },
        q3: "When do you want to start?",
        q3Options: { "this-month": "This month", "2-months": "Within two months", "this-quarter": "This quarter" },
        resultTitle: "Our recommendation",
        why: {
            "start-ai": "Without a clear target, a sprint is the cheapest way to avoid building the wrong thing. The roadmap becomes the brief for your first pilot.",
            "middle-scale": "One process, one or two systems: this is exactly what the pilot is scoped for. You get a working automation and real numbers in three weeks.",
            "automation-platform": "Several processes and three or more systems need an integration layer and a dashboard, not a chain of single automations.",
            "ent-assistant": "Questions answered from documents are a retrieval problem, not an automation problem. The assistant package is built for that.",
        } as Record<PackageId, string>,
        startNote: {
            "this-month": "We can kick off within a few working days of confirmed payment.",
            "2-months": "Book now to reserve a slot; kickoff is scheduled on payment.",
            "this-quarter": "Consider starting with the sprint now and scheduling the build for later in the quarter.",
        },
        reset: "Start over",
        goTo: "See package",
    },
    beyond: {
        eyebrow: "Beyond packages",
        title: "Custom development, retainers and AI on your own infrastructure",
        intro: "Packages cover the common cases. Everything else is scoped in a free 30-minute call and quoted as a fixed price or a monthly retainer.",
        items: [
            { title: "Custom AI & software", desc: "Multi-channel assistants, ML models on your data, internal tools, dashboards, web and mobile applications integrated with your systems." },
            { title: "AI operations retainer", desc: "A monthly block of engineer hours to keep automations and assistants running, add integrations and improve prompts and knowledge bases." },
            { title: "AI on your own servers", desc: "Open-source models on GPU servers in GDI managed colocation in Jakarta, with managed server operations — data never leaves your hardware." },
        ],
        colocationCta: "See GPU colocation and server operations",
        formTitle: "Tell us what you need",
        formIntro: "We reply within one working day with next steps or a call slot.",
    },
    process: {
        eyebrow: "How it works",
        title: "From order to handover",
        steps: [
            { title: "Choose and order", desc: "Add the package to your cart and pay by bank transfer using the order reference. No card required." },
            { title: "Kickoff", desc: "Within 2–3 working days of confirmed payment we schedule the kickoff, collect access and agree the success metric." },
            { title: "Weekly demos", desc: "You see progress every week. Scope changes are written down and quoted before any extra work starts." },
            { title: "Acceptance and handover", desc: "Delivery against the written scope, documentation, training and a handover session." },
            { title: "Support window", desc: "Bug fixes and questions are covered for the support period. After that, a retainer or ad-hoc hours." },
        ],
    },
    stack: {
        title: "What we build with",
        intro: "We pick tools per case and tell you why. No vendor lock-in to GDI: everything is deployed in your accounts or handed over.",
        groups: [
            { name: "Models", items: ["OpenAI", "Anthropic Claude", "Google Gemini", "Open-source (Llama, Qwen, Mistral) on your GPUs"] },
            { name: "Automation & integration", items: ["n8n", "Make", "Python / TypeScript services", "REST and webhook APIs"] },
            { name: "Channels", items: ["WhatsApp Business API", "Telegram", "Slack / Microsoft Teams", "Web widget"] },
            { name: "Systems we integrate", items: ["HubSpot, Salesforce, Odoo, custom CRM", "Google Workspace, Microsoft 365", "Meta Ads / Lead Ads", "Accounting and ERP via API"] },
        ],
    },
    industries: {
        eyebrow: "Typical use cases",
        title: "Where these packages are used",
        note: "Illustrative scenarios by industry, not client case studies.",
        items: [
            { name: "Retail & e-commerce", desc: "Order and return handling, product Q&A assistant, marketplace reporting." },
            { name: "Financial services", desc: "Document intake and pre-checks, KYC preparation, policy assistant for staff." },
            { name: "Logistics", desc: "Dispatch confirmations, tracking updates, driver document processing." },
            { name: "Education", desc: "Admissions inquiries, student support assistant, schedule and fee reminders." },
            { name: "Manufacturing", desc: "Shift reports, maintenance logs, supplier document processing." },
            { name: "Professional services", desc: "Proposal drafting, CRM hygiene, meeting notes to tasks." },
        ],
    },
    faq: {
        title: "Questions before ordering",
        items: [
            { q: "How do I pay?", a: "Add the package to your cart and complete the order. You receive bank transfer details and an order reference; we confirm the payment within one working day and schedule the kickoff. An invoice is issued by PT Global Digital Informasi." },
            { q: "Are the prices final?", a: "Yes for the scope described on this page. Prices exclude applicable taxes and third-party costs such as LLM API usage or automation-platform subscriptions. Additional scope is quoted in writing before we start it." },
            { q: "Who owns the code, prompts and data?", a: "You do. Everything is deployed in your accounts or handed over with documentation. We sign an NDA on request." },
            { q: "Where does the assistant or automation run?", a: "In your cloud accounts, on our managed cloud, or on your own servers in GDI managed colocation in Jakarta if data must stay on your hardware." },
            { q: "Which languages do you work in?", a: "English and Bahasa Indonesia for delivery and documentation. Assistants can answer in any language the chosen model supports." },
            { q: "What if the scope changes during the project?", a: "We write the change down, estimate it and send a quote. Nothing extra is built until you approve it." },
            { q: "Can I get a refund?", a: "Before delivery has started, yes, according to our Refund Policy. Once consultations or build work have begun, the policy applies as published." },
            { q: "Can we start faster or run two packages in parallel?", a: "Usually yes. Tell us in the order notes or the request form and we confirm the schedule before payment." },
        ],
    },
    finalCta: {
        h2: "Ready to put AI to work?",
        copy: "Order a package today or send us your case. Either way, you talk to the engineers who will do the work.",
        primary: "Compare packages",
        secondary: "Send a request",
        micro: "Fixed scope • fixed price • Jakarta-based, global delivery",
    },
    disclaimer: "Package prices are fixed for the scope described on this page and exclude applicable taxes and third-party services (model API usage, automation platforms, messaging APIs, hosting). Delivery times are working days from kickoff and assume timely access to systems and stakeholders.",
    lead: {
        fields: { name: "Full name", company: "Company", email: "Work email", phone: "WhatsApp / phone", interest: "I am interested in", package: "Related package (optional)", budget: "Budget range (optional)", timeline: "Timeline", message: "Describe your case" },
        interests: { "custom-ai": "Custom AI or ML solution", "custom-software": "Custom software / integration", retainer: "Monthly AI operations retainer", "own-infrastructure": "AI on my own GPU servers", "package-question": "Question about a package" },
        budgets: { "under-25m": "Under Rp 25,000,000", "25-75m": "Rp 25,000,000 – 75,000,000", "75-200m": "Rp 75,000,000 – 200,000,000", "over-200m": "Over Rp 200,000,000", "not-sure": "Not sure yet" },
        timelines: { asap: "As soon as possible", "1-2-months": "In 1–2 months", "this-quarter": "This quarter", exploring: "Just exploring" },
        none: "— none —",
        submit: "Send request",
        sending: "Sending…",
        success: "Thank you. We will reply within one working day.",
        error: "Could not send the request. Please try again or email info@gdiconsult.online.",
        required: "Please fill in all required fields.",
        privacy: "By sending this request you agree to be contacted by GDI about your enquiry.",
    },
};

export type ServicesContent = typeof en;

const id: ServicesContent = {
    meta: {
        title: "Layanan & Paket AI | Cakupan Tetap, Harga Tetap | GDI Consult",
        description: "AI readiness sprint, automation pilot, automation program dan private AI assistant — layanan AI dengan cakupan tetap untuk bisnis di Indonesia dan global, dikerjakan oleh Global Digital Informasi.",
    },
    nav: "Layanan AI",
    hero: {
        eyebrow: "Layanan AI • Cakupan Tetap • Harga Tetap",
        h1: "Layanan AI yang selesai dalam hitungan minggu, bukan kuartal",
        p1: "Empat paket dengan cakupan yang jelas, harga tetap dan tanggal serah terima — dari readiness sprint 7 hari hingga asisten AI privat di atas data perusahaan Anda.",
        p2: "Setiap paket dikerjakan oleh tim GDI yang sama yang mengelola infrastruktur Anda: hasilnya perangkat lunak yang berjalan, dokumentasi dan tim yang terlatih, bukan sekadar presentasi.",
        ctaPrimary: "Bandingkan paket",
        ctaSecondary: "Temukan paket saya",
        micro: "Transfer bank • kickoff dalam 2–3 hari kerja • kode dan data tetap milik Anda",
    },
    trust: [
        { title: "Cakupan tetap, harga tetap", desc: "Anda tahu apa yang didapat dan berapa biayanya sebelum membayar. Perubahan selalu ditawarkan tertulis, tanpa kejutan." },
        { title: "Perangkat lunak yang berjalan", desc: "Pilot dan program berakhir dengan otomatisasi yang berjalan di akun dan sistem Anda sendiri." },
        { title: "Data dan kode milik Anda", desc: "Kode sumber, prompt, workflow dan data adalah milik Anda. NDA tersedia atas permintaan." },
        { title: "Perangkat lunak + infrastruktur", desc: "Jalankan model di cloud kami, cloud Anda, atau di server GPU Anda sendiri di colocation terkelola GDI." },
    ],
    packagesSection: {
        eyebrow: "Paket",
        title: "Pilih paket yang sesuai posisi Anda saat ini",
        intro: "Mulai dari sprint jika belum yakin di mana AI memberi hasil. Langsung ke pilot jika sudah ada satu proses yang menyita waktu. Program dan asisten untuk tim yang siap mengubah cara kerja satu departemen.",
        from: "Harga tetap",
        exclTax: "belum termasuk pajak",
        duration: "Pengerjaan",
        workingDays: "hari kerja",
        weeks: "minggu",
        buy: "Pesan paket ini",
        details: "Lihat cakupan lengkap",
        discuss: "Ajukan pertanyaan",
        featured: "Titik awal paling sering dipilih",
        nextStep: "Langkah berikutnya",
    },
    packages: {
        "start-ai": {
            tagline: "Ketahui di mana AI memberi hasil di perusahaan Anda — dalam 7 hari kerja.",
            forWho: "Perusahaan dengan 10–500 karyawan yang belum memulai AI, atau sudah mencoba alat yang tersebar dan tidak dipakai.",
            problem: "Anda tahu AI bisa membantu, tetapi tidak tahu di mana, urutannya, atau biayanya. Membeli alat sebelum menjawab itu biasanya berakhir dengan lisensi yang tidak terpakai.",
            whatWeDo: [
                "Wawancara dengan pemilik 1–2 departemen (hingga 4 sesi) dan pemetaan proses utama mereka",
                "Audit alat, sumber data dan integrasi saat ini: apa yang bisa dihubungkan, apa yang tidak",
                "4–6 use case AI / otomatisasi konkret, masing-masing dinilai dari penghematan, upaya dan risiko",
                "Roadmap 6 bulan: apa yang dibangun dulu, apa yang dibeli, apa yang ditunda",
                "Sesi pemaparan dengan manajemen dan jawaban tertulis untuk pertanyaan lanjutan",
            ],
            deliverables: [
                "Laporan kesiapan AI (PDF, 15–25 halaman) dengan peta proses dan audit alat",
                "Backlog use case dengan logika ROI dan estimasi upaya per kasus",
                "Roadmap implementasi 6 bulan dengan rentang anggaran",
                "Sesi pemaparan 60 menit (online), termasuk rekaman",
            ],
            timeline: [
                { when: "Hari 1", what: "Kickoff, akses dokumen dan alat, jadwal wawancara" },
                { when: "Hari 2–4", what: "Wawancara, pemetaan proses, audit alat dan data" },
                { when: "Hari 5–6", what: "Penilaian use case, roadmap, rentang anggaran" },
                { when: "Hari 7", what: "Penyerahan laporan dan pemaparan ke manajemen" },
            ],
            youProvide: ["2–4 jam waktu pemangku kepentingan selama seminggu", "Contoh dokumen dan akses baca ke alat yang Anda gunakan", "Satu pengambil keputusan untuk sesi pemaparan"],
            notIncluded: ["Implementasi use case (itu bagian Automation Pilot)", "Lisensi perangkat lunak atau biaya API"],
            outcome: "Rencana yang terprioritas dan terhitung biayanya — plus brief pilot yang siap dimulai minggu berikutnya.",
        },
        "middle-scale": {
            tagline: "Satu otomatisasi, dibangun dan berjalan di alur kerja Anda dalam 3 minggu.",
            forWho: "Tim dengan satu proses berulang yang jelas menyita waktu: intake dokumen, kualifikasi lead, penanganan order atau tiket, laporan mingguan, balasan pelanggan.",
            problem: "Proses itu menghabiskan jam kerja setiap hari dan semua orang tahu, tetapi tidak ada yang sempat mengotomatiskannya dengan benar dan menjaganya tetap berjalan.",
            whatWeDo: [
                "Sesi scoping (atau roadmap dari Readiness Sprint) untuk menetapkan proses, input, output dan metrik keberhasilan",
                "Desain dan pembangunan satu workflow AI / otomatisasi dengan hingga 2 integrasi (mis. Gmail, Google Sheets, WhatsApp, CRM, akuntansi)",
                "Pengujian dengan data nyata bersama pemilik proses, penanganan error dan notifikasi",
                "Rollout ke tim, satu sesi pelatihan, panduan pengguna",
                "Dukungan perbaikan bug 30 hari setelah go-live",
            ],
            deliverables: [
                "Otomatisasi yang berjalan di akun Anda (n8n / Make / kode kustom — pilihan Anda)",
                "Hingga 2 integrasi sistem dengan monitoring dan peringatan error",
                "Panduan pengguna dan dokumentasi serah terima teknis",
                "Sesi pelatihan 90 menit untuk hingga 5 pengguna",
                "Jendela dukungan 30 hari dengan engineer yang ditunjuk",
            ],
            timeline: [
                { when: "Minggu 1", what: "Scoping, desain proses, akses sistem, data uji" },
                { when: "Minggu 2", what: "Pembangunan, integrasi, pengujian data nyata bersama pemilik proses" },
                { when: "Minggu 3", what: "Rollout, pelatihan, dokumentasi, serah terima" },
            ],
            youProvide: ["Pemilik proses yang tersedia ~2 jam per minggu", "Akses ke sistem yang disentuh workflow", "Data contoh untuk pengujian"],
            notIncluded: ["Langganan pihak ketiga (API LLM, platform otomatisasi, WhatsApp Business API)", "Lebih dari 2 integrasi (ditawarkan per integrasi)"],
            outcome: "Proses terukur yang berjalan tanpa serah terima manual — dan angka untuk memutuskan apa yang diotomatiskan berikutnya.",
        },
        "automation-platform": {
            tagline: "Hingga tiga otomatisasi terhubung untuk satu departemen, terintegrasi dengan CRM, ERP dan alat Anda.",
            forWho: "Tim operasional, penjualan, keuangan atau layanan pelanggan dengan banyak serah terima manual — atau perusahaan setelah pilot yang berhasil.",
            problem: "Otomatisasi tunggal membantu, tetapi biaya sebenarnya ada di antara sistem: mengetik ulang data, mengejar persetujuan, membuat laporan yang sama di tiga alat.",
            whatWeDo: [
                "Pemetaan proses satu departemen: serah terima, pemilik, sistem, volume",
                "Arsitektur untuk hingga 3 workflow terhubung dan hingga 5 integrasi (CRM, ERP, Google Workspace, Meta, WhatsApp, akuntansi, database internal)",
                "Pembangunan, rollout bertahap dan user acceptance testing bersama tim Anda",
                "Dasbor terpusat: eksekusi, error, volume, waktu yang dihemat; akses berbasis peran",
                "Runbook, dokumentasi, dua sesi pelatihan dan dukungan 30 hari",
            ],
            deliverables: [
                "3 otomatisasi produksi dengan lapisan integrasi bersama",
                "Hingga 5 integrasi sistem dengan monitoring dan peringatan",
                "Dasbor operasional dan baseline KPI bulanan vs. pengukuran sesudahnya",
                "Runbook, arsitektur dan dokumentasi serah terima",
                "2 sesi pelatihan (pengguna dan admin internal)",
                "Jendela dukungan 30 hari",
            ],
            timeline: [
                { when: "Minggu 1–2", what: "Pemetaan proses, arsitektur, akses integrasi" },
                { when: "Minggu 3–5", what: "Pembangunan dan pengujian internal, demo mingguan" },
                { when: "Minggu 6", what: "User acceptance testing bersama tim Anda" },
                { when: "Minggu 7–8", what: "Rollout, pelatihan, pengukuran, serah terima" },
            ],
            youProvide: ["Kepala departemen dan satu power user, ~2–3 jam per minggu", "Akses ke sistem dan kredensial API", "Persetujuan peta proses di minggu ke-2"],
            notIncluded: ["Lisensi, hosting dan penggunaan API", "Pelatihan model ML kustom (lihat pengembangan kustom)", "Lebih dari 5 integrasi (ditawarkan per integrasi)"],
            outcome: "Departemen di mana data berpindah antar sistem dengan sendirinya, dengan dasbor yang menunjukkan jam yang dihemat setiap bulan.",
        },
        "ent-assistant": {
            tagline: "Asisten AI privat yang menjawab dari dokumen, kebijakan dan data produk Anda — untuk satu departemen, di satu kanal.",
            forWho: "Tim layanan pelanggan, penjualan, HR, legal atau pengetahuan internal dengan basis dokumen, kebijakan, katalog atau manual yang terus ditanyakan orang.",
            problem: "Jawabannya ada di suatu tempat di PDF, drive dan riwayat chat, tetapi mencarinya memakan menit setiap kali dan kualitasnya tergantung siapa yang sedang bertugas.",
            whatWeDo: [
                "Discovery: use case, kebijakan jawaban, apa yang tidak boleh dilakukan asisten",
                "Pipeline basis pengetahuan (retrieval-augmented generation) dari dokumen Anda — hingga 500 dokumen / 5.000 halaman, dengan pembaruan terjadwal",
                "Asisten di satu kanal pilihan Anda: widget web, WhatsApp, Telegram, Slack atau Microsoft Teams",
                "Akses berbasis peran, guardrail, kutipan sumber, eskalasi ke manusia",
                "Panel analitik: pertanyaan, kualitas jawaban, celah di basis pengetahuan",
                "Pilot bersama departemen, penyetelan, panduan penggunaan, pelatihan, 30 hari penyetelan setelah rollout",
            ],
            deliverables: [
                "Asisten aktif di 1 kanal untuk 1 departemen",
                "Pipeline basis pengetahuan dengan jadwal pembaruan dan kontrol akses",
                "Panel admin dengan analitik dan tinjauan percakapan",
                "Dokumen panduan penggunaan dan kebijakan jawaban",
                "2 sesi pelatihan (pengguna dan pemilik konten)",
                "Jendela penyetelan dan dukungan 30 hari",
            ],
            timeline: [
                { when: "Minggu 1", what: "Discovery, pengumpulan dokumen, kebijakan jawaban" },
                { when: "Minggu 2–3", what: "Pipeline pengetahuan, pembangunan asisten, integrasi kanal" },
                { when: "Minggu 4", what: "Pilot bersama departemen, tinjauan percakapan nyata" },
                { when: "Minggu 5–6", what: "Penyetelan, rollout, pelatihan, serah terima" },
            ],
            youProvide: ["Pemilik konten yang bisa memastikan dokumen mana yang terkini", "Kelompok pilot 5–15 pengguna", "Akun kanal (mis. WhatsApp Business) jika tidak memakai widget web"],
            notIncluded: ["Penggunaan API LLM dan hosting (atau jalankan di server GPU Anda sendiri di colocation GDI)", "Kanal atau departemen tambahan (ditawarkan)", "Fine-tuning model kustom"],
            outcome: "Jawaban konsisten dengan kutipan dalam hitungan detik, jejak audit setiap percakapan, dan basis pengetahuan yang akhirnya punya pemilik.",
        },
    },
    compare: {
        eyebrow: "Bandingkan",
        title: "Empat paket berdampingan",
        rows: {
            duration: "Waktu pengerjaan",
            yourTime: "Waktu tim Anda",
            result: "Yang Anda dapatkan",
            integrations: "Integrasi termasuk",
            training: "Sesi pelatihan",
            support: "Dukungan setelah serah terima",
            price: "Harga tetap",
        },
        results: {
            "start-ai": "Laporan, backlog use case, roadmap 6 bulan",
            "middle-scale": "1 otomatisasi aktif di alur kerja Anda",
            "automation-platform": "3 otomatisasi terhubung + dasbor",
            "ent-assistant": "Asisten AI di atas dokumen Anda, 1 kanal",
        },
        hours: "jam",
        days: "hari",
        none: "—",
    },
    finder: {
        eyebrow: "Belum yakin?",
        title: "Temukan paket Anda dalam tiga pertanyaan",
        q1: "Di mana posisi perusahaan Anda dengan AI saat ini?",
        q1Options: {
            unsure: "Belum mulai, atau belum yakin di mana AI memberi hasil",
            "one-process": "Ada satu proses jelas yang terlalu menyita waktu",
            department: "Satu departemen penuh berjalan dengan serah terima manual antar sistem",
            knowledge: "Orang terus bertanya hal yang sebenarnya sudah dijawab di dokumen kami",
        },
        q2: "Berapa sistem yang perlu dihubungkan?",
        q2Options: { "0-1": "Tidak ada atau satu", "2": "Dua", "3-5": "Tiga sampai lima", "not-sure": "Belum tahu" },
        q3: "Kapan Anda ingin mulai?",
        q3Options: { "this-month": "Bulan ini", "2-months": "Dalam dua bulan", "this-quarter": "Kuartal ini" },
        resultTitle: "Rekomendasi kami",
        why: {
            "start-ai": "Tanpa target yang jelas, sprint adalah cara termurah menghindari membangun hal yang salah. Roadmap-nya menjadi brief untuk pilot pertama Anda.",
            "middle-scale": "Satu proses, satu atau dua sistem: persis cakupan pilot. Anda mendapat otomatisasi yang berjalan dan angka nyata dalam tiga minggu.",
            "automation-platform": "Beberapa proses dan tiga sistem atau lebih membutuhkan lapisan integrasi dan dasbor, bukan rangkaian otomatisasi tunggal.",
            "ent-assistant": "Pertanyaan yang dijawab dari dokumen adalah masalah pencarian, bukan otomatisasi. Paket asisten dibangun untuk itu.",
        },
        startNote: {
            "this-month": "Kami bisa kickoff dalam beberapa hari kerja setelah pembayaran dikonfirmasi.",
            "2-months": "Pesan sekarang untuk mengamankan slot; kickoff dijadwalkan saat pembayaran.",
            "this-quarter": "Pertimbangkan memulai sprint sekarang dan menjadwalkan pembangunan di akhir kuartal.",
        },
        reset: "Ulangi",
        goTo: "Lihat paket",
    },
    beyond: {
        eyebrow: "Di luar paket",
        title: "Pengembangan kustom, retainer dan AI di infrastruktur Anda sendiri",
        intro: "Paket mencakup kasus umum. Selebihnya dibahas dalam panggilan 30 menit gratis dan ditawarkan sebagai harga tetap atau retainer bulanan.",
        items: [
            { title: "AI & perangkat lunak kustom", desc: "Asisten multi-kanal, model ML di atas data Anda, alat internal, dasbor, aplikasi web dan mobile yang terintegrasi dengan sistem Anda." },
            { title: "Retainer operasional AI", desc: "Blok jam engineer bulanan untuk menjaga otomatisasi dan asisten tetap berjalan, menambah integrasi serta menyempurnakan prompt dan basis pengetahuan." },
            { title: "AI di server Anda sendiri", desc: "Model open-source di server GPU di colocation terkelola GDI Jakarta, dengan operasional server terkelola — data tidak pernah meninggalkan perangkat keras Anda." },
        ],
        colocationCta: "Lihat colocation GPU dan operasional server",
        formTitle: "Ceritakan kebutuhan Anda",
        formIntro: "Kami membalas dalam satu hari kerja dengan langkah berikutnya atau jadwal panggilan.",
    },
    process: {
        eyebrow: "Cara kerjanya",
        title: "Dari pemesanan hingga serah terima",
        steps: [
            { title: "Pilih dan pesan", desc: "Tambahkan paket ke keranjang dan bayar via transfer bank dengan referensi pesanan. Tanpa kartu kredit." },
            { title: "Kickoff", desc: "Dalam 2–3 hari kerja setelah pembayaran dikonfirmasi kami menjadwalkan kickoff, mengumpulkan akses dan menyepakati metrik keberhasilan." },
            { title: "Demo mingguan", desc: "Anda melihat progres setiap minggu. Perubahan cakupan ditulis dan ditawarkan sebelum pekerjaan tambahan dimulai." },
            { title: "Penerimaan dan serah terima", desc: "Penyerahan sesuai cakupan tertulis, dokumentasi, pelatihan dan sesi serah terima." },
            { title: "Jendela dukungan", desc: "Perbaikan bug dan pertanyaan ditanggung selama periode dukungan. Setelah itu, retainer atau jam ad-hoc." },
        ],
    },
    stack: {
        title: "Alat yang kami gunakan",
        intro: "Kami memilih alat per kasus dan menjelaskan alasannya. Tanpa ketergantungan pada GDI: semuanya dipasang di akun Anda atau diserahterimakan.",
        groups: [
            { name: "Model", items: ["OpenAI", "Anthropic Claude", "Google Gemini", "Open-source (Llama, Qwen, Mistral) di GPU Anda"] },
            { name: "Otomatisasi & integrasi", items: ["n8n", "Make", "Layanan Python / TypeScript", "REST dan webhook API"] },
            { name: "Kanal", items: ["WhatsApp Business API", "Telegram", "Slack / Microsoft Teams", "Widget web"] },
            { name: "Sistem yang kami integrasikan", items: ["HubSpot, Salesforce, Odoo, CRM kustom", "Google Workspace, Microsoft 365", "Meta Ads / Lead Ads", "Akuntansi dan ERP via API"] },
        ],
    },
    industries: {
        eyebrow: "Contoh penggunaan",
        title: "Di mana paket ini digunakan",
        note: "Skenario ilustratif per industri, bukan studi kasus klien.",
        items: [
            { name: "Ritel & e-commerce", desc: "Penanganan order dan retur, asisten tanya jawab produk, laporan marketplace." },
            { name: "Jasa keuangan", desc: "Intake dokumen dan pra-pemeriksaan, persiapan KYC, asisten kebijakan untuk staf." },
            { name: "Logistik", desc: "Konfirmasi pengiriman, pembaruan pelacakan, pemrosesan dokumen pengemudi." },
            { name: "Pendidikan", desc: "Pertanyaan pendaftaran, asisten dukungan siswa, pengingat jadwal dan biaya." },
            { name: "Manufaktur", desc: "Laporan shift, log pemeliharaan, pemrosesan dokumen pemasok." },
            { name: "Jasa profesional", desc: "Penyusunan proposal, kebersihan data CRM, catatan rapat menjadi tugas." },
        ],
    },
    faq: {
        title: "Pertanyaan sebelum memesan",
        items: [
            { q: "Bagaimana cara membayar?", a: "Tambahkan paket ke keranjang dan selesaikan pesanan. Anda menerima rincian transfer bank dan referensi pesanan; kami mengonfirmasi pembayaran dalam satu hari kerja dan menjadwalkan kickoff. Faktur diterbitkan oleh PT Global Digital Informasi." },
            { q: "Apakah harganya final?", a: "Ya untuk cakupan yang dijelaskan di halaman ini. Harga belum termasuk pajak yang berlaku dan biaya pihak ketiga seperti penggunaan API LLM atau langganan platform otomatisasi. Cakupan tambahan ditawarkan tertulis sebelum kami mulai." },
            { q: "Siapa pemilik kode, prompt dan data?", a: "Anda. Semuanya dipasang di akun Anda atau diserahterimakan dengan dokumentasi. Kami menandatangani NDA atas permintaan." },
            { q: "Di mana asisten atau otomatisasi berjalan?", a: "Di akun cloud Anda, di cloud terkelola kami, atau di server Anda sendiri di colocation terkelola GDI Jakarta jika data harus tetap di perangkat keras Anda." },
            { q: "Bahasa apa yang digunakan?", a: "Bahasa Inggris dan Bahasa Indonesia untuk pengerjaan dan dokumentasi. Asisten dapat menjawab dalam bahasa apa pun yang didukung model yang dipilih." },
            { q: "Bagaimana jika cakupan berubah selama proyek?", a: "Kami menuliskannya, mengestimasi dan mengirim penawaran. Tidak ada pekerjaan tambahan sebelum Anda menyetujuinya." },
            { q: "Bisakah saya mendapat pengembalian dana?", a: "Sebelum pengerjaan dimulai, ya, sesuai Kebijakan Pengembalian Dana kami. Setelah konsultasi atau pembangunan dimulai, kebijakan berlaku sebagaimana dipublikasikan." },
            { q: "Bisakah mulai lebih cepat atau menjalankan dua paket sekaligus?", a: "Biasanya bisa. Sampaikan di catatan pesanan atau formulir permintaan dan kami konfirmasi jadwal sebelum pembayaran." },
        ],
    },
    finalCta: {
        h2: "Siap membuat AI bekerja untuk Anda?",
        copy: "Pesan paket hari ini atau kirimkan kasus Anda. Apa pun pilihannya, Anda berbicara langsung dengan engineer yang akan mengerjakannya.",
        primary: "Bandingkan paket",
        secondary: "Kirim permintaan",
        micro: "Cakupan tetap • harga tetap • berbasis Jakarta, pengerjaan global",
    },
    disclaimer: "Harga paket tetap untuk cakupan yang dijelaskan di halaman ini dan belum termasuk pajak yang berlaku serta layanan pihak ketiga (penggunaan API model, platform otomatisasi, API pesan, hosting). Waktu pengerjaan dalam hari kerja sejak kickoff dan mengasumsikan akses tepat waktu ke sistem dan pemangku kepentingan.",
    lead: {
        fields: { name: "Nama lengkap", company: "Perusahaan", email: "Email kerja", phone: "WhatsApp / telepon", interest: "Saya tertarik pada", package: "Paket terkait (opsional)", budget: "Rentang anggaran (opsional)", timeline: "Waktu", message: "Ceritakan kasus Anda" },
        interests: { "custom-ai": "Solusi AI atau ML kustom", "custom-software": "Perangkat lunak / integrasi kustom", retainer: "Retainer operasional AI bulanan", "own-infrastructure": "AI di server GPU saya sendiri", "package-question": "Pertanyaan tentang paket" },
        budgets: { "under-25m": "Di bawah Rp 25.000.000", "25-75m": "Rp 25.000.000 – 75.000.000", "75-200m": "Rp 75.000.000 – 200.000.000", "over-200m": "Di atas Rp 200.000.000", "not-sure": "Belum tahu" },
        timelines: { asap: "Sesegera mungkin", "1-2-months": "Dalam 1–2 bulan", "this-quarter": "Kuartal ini", exploring: "Masih menjajaki" },
        none: "— tidak ada —",
        submit: "Kirim permintaan",
        sending: "Mengirim…",
        success: "Terima kasih. Kami akan membalas dalam satu hari kerja.",
        error: "Permintaan tidak dapat dikirim. Silakan coba lagi atau email info@gdiconsult.online.",
        required: "Mohon lengkapi semua kolom wajib.",
        privacy: "Dengan mengirim permintaan ini Anda setuju dihubungi GDI terkait pertanyaan Anda.",
    },
};

export const servicesContent = { en, id } as const;
export type ServicesLang = keyof typeof servicesContent;
